<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-11-10T18:30:19+09:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      api_keys.google.maps
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Asia/Tokyo',
    'api_keys' => [
        'google' => [
            'maps' => '',
        ],
    ],
];
