<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-01-23T16:01:44+09:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.latest_version
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'locale' => 'ja_JP',
    'version_installed' => '8.2.1',
    'version_db_installed' => '20170802000000',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1510306226,
        'latest_version' => '8.3.2',
        'do_page_reindex_check' => false,
    ],
    'cache' => [
        'clear' => [
            'thumbnails' => false,
        ],
    ],
];
