<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-11-10T18:27:42+09:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'テスト',
        ],
    ],
];
